[package]
name = "rscrn"
version = "0.1.0"
edition = "2024"

[dependencies]
rdev = "0.5.3"
clap = { version = "4.5.32", default-features = false, features = ["std", "derive", "help", "color", "usage", "error-context"] }

[profile.release]
lto = true
codegen-units = 1
strip = true